---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voteapp
  annotations:
  labels:
    run: vote
  name: vote-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vote
  template:
    metadata:
      labels:
        run: vote
    spec:
      containers:
      - image: dansolo7/voting:$BUILD_NUMBER
        imagePullPolicy: Always
        name: vote
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: voteapp-secret
              key: aws_access_key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: voteapp-secret
              key: aws_secret_key
        - name: AWS_REGION
          value: "us-east-1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: voteapp
  labels:
    run: vote
  name: vote-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80 # Criada para intra cluster. Para Fazer o bind
    protocol: TCP
    targetPort: 80 # Porta do container
  selector:
    run: vote
  sessionAffinity: None
  type: NodePort
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: voteapp
    name: vote-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
  spec:
    rules:
    - host: www.vote.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vote-service # Selecting Service
              servicePort: 80
